[2024-05-07T23:55:18.359-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-07T23:55:18.389-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xcom_dag.read_players manual__2024-05-08T02:53:12.079583+00:00 [queued]>
[2024-05-07T23:55:18.403-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xcom_dag.read_players manual__2024-05-08T02:53:12.079583+00:00 [queued]>
[2024-05-07T23:55:18.404-0300] {taskinstance.py:2303} INFO - Starting attempt 2 of 1
[2024-05-07T23:55:18.447-0300] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): read_players> on 2024-05-08 02:53:12.079583+00:00
[2024-05-07T23:55:18.450-0300] {standard_task_runner.py:63} INFO - Started process 6770 to run task
[2024-05-07T23:55:18.453-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'xcom_dag', 'read_players', 'manual__2024-05-08T02:53:12.079583+00:00', '--job-id', '1219', '--raw', '--subdir', 'DAGS_FOLDER/xcom_dag.py', '--cfg-path', '/tmp/tmpkr7jdqr7']
[2024-05-07T23:55:18.455-0300] {standard_task_runner.py:91} INFO - Job 1219: Subtask read_players
[2024-05-07T23:55:18.532-0300] {task_command.py:426} INFO - Running <TaskInstance: xcom_dag.read_players manual__2024-05-08T02:53:12.079583+00:00 [running]> on host PC-Tilto.
[2024-05-07T23:55:18.722-0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='xcom_dag' AIRFLOW_CTX_TASK_ID='read_players' AIRFLOW_CTX_EXECUTION_DATE='2024-05-08T02:53:12.079583+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-08T02:53:12.079583+00:00'
[2024-05-07T23:55:18.723-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-07T23:55:18.734-0300] {postgres.py:175} INFO - Running copy expert: COPY (SELECT * FROM players) TO stdout WITH CSV HEADER, filename: /mnt/c/Users/Tilto/Desktop/Work/Airflow//data/players.csv
[2024-05-07T23:55:18.749-0300] {base.py:84} INFO - Using connection ID 'PG_SWORDBLAST' for task execution.
[2024-05-07T23:57:30.602-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-07T23:57:30.605-0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py", line 12, in read_players
    pghook.copy_expert(
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/postgres/hooks/postgres.py", line 180, in copy_expert
    with open(filename, "r+") as file, closing(self.get_conn()) as conn, closing(conn.cursor()) as cur:
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/postgres/hooks/postgres.py", line 161, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/usr/local/lib/python3.10/dist-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "172.16.2.201", port 5432 failed: Connection timed out
	Is the server running on that host and accepting TCP/IP connections?

[2024-05-07T23:57:30.634-0300] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=xcom_dag, task_id=read_players, execution_date=20240508T025312, start_date=20240508T025518, end_date=20240508T025730
[2024-05-07T23:57:30.677-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 1219 for task read_players (connection to server at "172.16.2.201", port 5432 failed: Connection timed out
	Is the server running on that host and accepting TCP/IP connections?
; 6770)
[2024-05-07T23:57:30.691-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-07T23:57:30.709-0300] {logging_mixin.py:188} WARNING - /usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-05-07T23:57:30.724-0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-07T23:57:30.746-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
