[2024-05-07T18:01:10.906-0300] {processor.py:161} INFO - Started process (PID=2162) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:01:10.908-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:01:10.910-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:01:10.909-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:01:10.929-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:01:10.929-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py", line 14
    start_date=datetime(2020,01,01)
                             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-05-07T18:01:10.930-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:01:10.968-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.068 seconds
[2024-05-07T18:03:26.412-0300] {processor.py:161} INFO - Started process (PID=2718) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:03:26.413-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:03:26.414-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:03:26.414-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:03:26.431-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:03:26.431-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py", line 14
    start_date=datetime(2020,01,01)
                             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-05-07T18:03:26.432-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:03:26.467-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.060 seconds
[2024-05-07T18:03:56.713-0300] {processor.py:161} INFO - Started process (PID=2859) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:03:56.714-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:03:56.715-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:03:56.715-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:03:56.732-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:03:56.732-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py", line 14
    start_date=datetime(2020,01,01)
                             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-05-07T18:03:56.733-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:03:56.766-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.057 seconds
[2024-05-07T18:04:12.987-0300] {processor.py:161} INFO - Started process (PID=3007) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:04:12.988-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:04:12.989-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:04:12.988-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:04:13.012-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:04:13.012-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py", line 16
    start_date=datetime(2020,01,01)
                             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-05-07T18:04:13.013-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:04:13.053-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.070 seconds
[2024-05-07T18:04:43.572-0300] {processor.py:161} INFO - Started process (PID=3135) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:04:43.573-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:04:43.574-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:04:43.574-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:04:43.592-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:04:43.591-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py", line 16
    start_date=datetime(2020,01,01)
                             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-05-07T18:04:43.592-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:04:43.627-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.059 seconds
[2024-05-07T18:05:13.908-0300] {processor.py:161} INFO - Started process (PID=3262) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:05:13.909-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:05:13.910-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:05:13.910-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:05:13.928-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:05:13.927-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py", line 16
    start_date=datetime(2020,01,01)
                             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-05-07T18:05:13.928-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:05:13.963-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.059 seconds
[2024-05-07T18:05:44.618-0300] {processor.py:161} INFO - Started process (PID=3390) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:05:44.619-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:05:44.620-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:05:44.620-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:05:44.637-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:05:44.636-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py", line 16
    start_date=datetime(2020,01,01)
                             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-05-07T18:05:44.637-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:05:44.670-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.056 seconds
[2024-05-07T18:05:59.061-0300] {processor.py:161} INFO - Started process (PID=3450) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:05:59.062-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:05:59.063-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:05:59.063-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:05:59.087-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:05:59.086-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py", line 20
    start_date=datetime(2020,01,01)
                             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-05-07T18:05:59.088-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:05:59.135-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.080 seconds
[2024-05-07T18:06:30.020-0300] {processor.py:161} INFO - Started process (PID=3580) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:06:30.021-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:06:30.022-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:06:30.021-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:06:30.039-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:06:30.038-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py", line 20
    start_date=datetime(2020,01,01)
                             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-05-07T18:06:30.039-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:06:30.143-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.128 seconds
[2024-05-07T18:17:54.862-0300] {processor.py:161} INFO - Started process (PID=6322) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:17:54.863-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:17:54.865-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:17:54.865-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:17:54.888-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:17:54.887-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py", line 29
    start_date=datetime(2020,01,01)
                             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-05-07T18:17:54.889-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:17:54.930-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.074 seconds
[2024-05-07T18:18:25.649-0300] {processor.py:161} INFO - Started process (PID=6460) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:18:25.650-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:18:25.652-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:18:25.652-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:18:25.673-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:18:25.672-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py", line 29
    start_date=datetime(2020,01,01)
                             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-05-07T18:18:25.674-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:18:25.707-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.066 seconds
[2024-05-07T18:18:55.818-0300] {processor.py:161} INFO - Started process (PID=6587) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:18:55.819-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:18:55.820-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:18:55.820-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:18:55.840-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:18:55.839-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py", line 29
    start_date=datetime(2020,01,01)
                             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-05-07T18:18:55.841-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:18:55.931-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.118 seconds
[2024-05-07T18:19:26.627-0300] {processor.py:161} INFO - Started process (PID=6716) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:19:26.628-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:19:26.629-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:19:26.629-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:19:26.647-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:19:26.646-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py", line 29
    start_date=datetime(2020,01,01)
                             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-05-07T18:19:26.648-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:19:26.686-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.063 seconds
[2024-05-07T18:19:37.299-0300] {processor.py:161} INFO - Started process (PID=6779) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:19:37.300-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:19:37.302-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:19:37.301-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:19:37.320-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:19:37.319-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py", line 29
    start_date=datetime(2020,01,01)
                             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-05-07T18:19:37.321-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:19:37.354-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.060 seconds
[2024-05-07T18:20:08.440-0300] {processor.py:161} INFO - Started process (PID=6925) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:20:08.441-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:20:08.443-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:20:08.442-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:20:08.458-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:20:08.457-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py", line 29
    start_date=datetime(2020,01,01)
                             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-05-07T18:20:08.459-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:20:08.489-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.053 seconds
[2024-05-07T18:20:39.114-0300] {processor.py:161} INFO - Started process (PID=7057) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:20:39.115-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:20:39.116-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:20:39.116-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:20:39.134-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:20:39.133-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py", line 29
    start_date=datetime(2020,01,01)
                             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-05-07T18:20:39.135-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:20:39.170-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.061 seconds
[2024-05-07T18:21:10.118-0300] {processor.py:161} INFO - Started process (PID=7202) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:21:10.119-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:21:10.121-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:21:10.121-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:21:10.141-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:21:10.141-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py", line 29
    start_date=datetime(2020,01,01)
                             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-05-07T18:21:10.142-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:21:10.184-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.070 seconds
[2024-05-07T18:48:26.604-0300] {processor.py:161} INFO - Started process (PID=13732) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:48:26.606-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:48:26.607-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:48:26.607-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:48:26.627-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:48:26.627-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py", line 41
    start_date=datetime(2020,01,01)
                             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-05-07T18:48:26.628-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:48:26.670-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.072 seconds
[2024-05-07T18:48:57.222-0300] {processor.py:161} INFO - Started process (PID=13872) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:48:57.223-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:48:57.225-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:48:57.225-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:48:57.242-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:48:57.242-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py", line 41
    start_date=datetime(2020,01,01)
                             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-05-07T18:48:57.243-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:48:57.279-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.062 seconds
[2024-05-07T18:49:28.280-0300] {processor.py:161} INFO - Started process (PID=14002) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:49:28.281-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:49:28.282-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:49:28.282-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:49:28.299-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:49:28.299-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py", line 41
    start_date=datetime(2020,01,01)
                             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-05-07T18:49:28.300-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:49:28.338-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.064 seconds
[2024-05-07T18:49:58.724-0300] {processor.py:161} INFO - Started process (PID=14130) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:49:58.725-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:49:58.727-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:49:58.726-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:49:58.744-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:49:58.743-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py", line 41
    start_date=datetime(2020,01,01)
                             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-05-07T18:49:58.745-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:49:58.777-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.058 seconds
[2024-05-07T18:50:29.274-0300] {processor.py:161} INFO - Started process (PID=14262) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:50:29.276-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:50:29.279-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:50:29.278-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:50:29.298-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:50:29.297-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py", line 41
    start_date=datetime(2020,01,01)
                             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-05-07T18:50:29.298-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:50:29.336-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.071 seconds
[2024-05-07T18:50:59.830-0300] {processor.py:161} INFO - Started process (PID=14390) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:50:59.831-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:50:59.833-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:50:59.833-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:50:59.852-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:50:59.851-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py", line 41
    start_date=datetime(2020,01,01)
                             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-05-07T18:50:59.853-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:50:59.892-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.066 seconds
[2024-05-07T18:51:15.744-0300] {processor.py:161} INFO - Started process (PID=14465) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:51:15.745-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:51:15.748-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:51:15.748-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:51:15.767-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:51:15.766-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py", line 41
    start_date=datetime(2020,1,01)
                               ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-05-07T18:51:15.767-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:51:15.805-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.067 seconds
[2024-05-07T18:51:16.961-0300] {processor.py:161} INFO - Started process (PID=14474) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:51:16.962-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:51:16.964-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:51:16.963-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:51:17.422-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:51:17.416-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py", line 64, in <module>
    task4 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2024-05-07T18:51:17.424-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:51:17.461-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.505 seconds
[2024-05-07T18:51:38.334-0300] {processor.py:161} INFO - Started process (PID=14604) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:51:38.335-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:51:38.336-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:51:38.336-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:51:38.802-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:51:38.798-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py", line 64, in <module>
    task4 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2024-05-07T18:51:38.805-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:51:38.838-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.508 seconds
[2024-05-07T18:52:10.090-0300] {processor.py:161} INFO - Started process (PID=14760) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:52:10.091-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:52:10.093-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:52:10.093-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:52:10.506-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:52:10.501-0300] {dagbag.py:350} ERROR - Failed to import: /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py", line 64, in <module>
    task4 = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2024-05-07T18:52:10.508-0300] {processor.py:842} WARNING - No viable dags retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:52:10.543-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.460 seconds
[2024-05-07T18:52:34.729-0300] {processor.py:161} INFO - Started process (PID=14876) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:52:34.730-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:52:34.732-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:52:34.732-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:52:35.172-0300] {processor.py:840} INFO - DAG(s) 'xcom_dag' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:52:35.308-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:52:35.307-0300] {override.py:1829} INFO - Created Permission View: can read on DAG:xcom_dag
[2024-05-07T18:52:35.344-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:52:35.343-0300] {override.py:1829} INFO - Created Permission View: can delete on DAG:xcom_dag
[2024-05-07T18:52:35.375-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:52:35.375-0300] {override.py:1829} INFO - Created Permission View: can edit on DAG:xcom_dag
[2024-05-07T18:52:35.376-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:52:35.376-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-07T18:52:35.391-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:52:35.391-0300] {dag.py:3118} INFO - Creating ORM DAG for xcom_dag
[2024-05-07T18:52:35.392-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:52:35.392-0300] {dag.py:3954} INFO - Setting next_dagrun for xcom_dag to None, run_after=None
[2024-05-07T18:52:35.477-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.757 seconds
[2024-05-07T18:52:47.651-0300] {processor.py:161} INFO - Started process (PID=14970) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:52:47.652-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:52:47.654-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:52:47.653-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:52:48.080-0300] {processor.py:840} INFO - DAG(s) 'xcom_dag' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:52:48.092-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:52:48.091-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-07T18:52:48.105-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:52:48.105-0300] {dag.py:3954} INFO - Setting next_dagrun for xcom_dag to None, run_after=None
[2024-05-07T18:52:48.163-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.520 seconds
[2024-05-07T18:53:19.190-0300] {processor.py:161} INFO - Started process (PID=15125) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:53:19.191-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:53:19.192-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:53:19.192-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:53:19.573-0300] {processor.py:840} INFO - DAG(s) 'xcom_dag' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:53:19.679-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:53:19.678-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-07T18:53:19.689-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:53:19.689-0300] {dag.py:3954} INFO - Setting next_dagrun for xcom_dag to None, run_after=None
[2024-05-07T18:53:19.751-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.566 seconds
[2024-05-07T18:53:50.587-0300] {processor.py:161} INFO - Started process (PID=15286) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:53:50.588-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:53:50.590-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:53:50.589-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:53:50.993-0300] {processor.py:840} INFO - DAG(s) 'xcom_dag' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:53:51.020-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:53:51.020-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-07T18:53:51.036-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:53:51.036-0300] {dag.py:3954} INFO - Setting next_dagrun for xcom_dag to None, run_after=None
[2024-05-07T18:53:51.099-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.517 seconds
[2024-05-07T18:54:22.204-0300] {processor.py:161} INFO - Started process (PID=15435) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:54:22.205-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:54:22.206-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:54:22.206-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:54:22.628-0300] {processor.py:840} INFO - DAG(s) 'xcom_dag' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:54:22.653-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:54:22.653-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-07T18:54:22.665-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:54:22.665-0300] {dag.py:3954} INFO - Setting next_dagrun for xcom_dag to None, run_after=None
[2024-05-07T18:54:22.724-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.524 seconds
[2024-05-07T18:54:53.349-0300] {processor.py:161} INFO - Started process (PID=15581) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:54:53.350-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:54:53.351-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:54:53.351-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:54:53.747-0300] {processor.py:840} INFO - DAG(s) 'xcom_dag' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:54:53.772-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:54:53.771-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-07T18:54:53.784-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:54:53.784-0300] {dag.py:3954} INFO - Setting next_dagrun for xcom_dag to None, run_after=None
[2024-05-07T18:54:53.848-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.505 seconds
[2024-05-07T18:55:24.605-0300] {processor.py:161} INFO - Started process (PID=15723) to work on /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:55:24.606-0300] {processor.py:830} INFO - Processing file /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py for tasks to queue
[2024-05-07T18:55:24.608-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:55:24.608-0300] {dagbag.py:540} INFO - Filling up the DagBag from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:55:24.979-0300] {processor.py:840} INFO - DAG(s) 'xcom_dag' retrieved from /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py
[2024-05-07T18:55:25.006-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:55:25.006-0300] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-07T18:55:25.019-0300] {logging_mixin.py:188} INFO - [2024-05-07T18:55:25.018-0300] {dag.py:3954} INFO - Setting next_dagrun for xcom_dag to None, run_after=None
[2024-05-07T18:55:25.078-0300] {processor.py:183} INFO - Processing /mnt/c/Users/Tilto/Desktop/Work/Airflow/dags/xcom_dag.py took 0.477 seconds
